//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoLends.Data
{
    using System;
    
    public enum Condition : int
    {
        Neuwertig = 0,
        Gebraucht = 1,
        Beschädigt = 2,
        Fehlerhaft = 3
    }
}
