//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoLends.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DependcyItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DependcyItems()
        {
            this.LendItem = new HashSet<LendItem>();
        }
    
        public int Id { get; set; }
        public int LendItemId { get; set; }
        public int DependendItemdId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LendItem> LendItem { get; set; }
    }
}
