//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoLends.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LendReturn
    {
        public int Id { get; set; }
        public int LendId { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int UserId { get; set; }
        public Nullable<int> LRId { get; set; }
    
        public virtual User User { get; set; }
        public virtual LR LR { get; set; }
    }
}
