//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoLends.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lend
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lend()
        {
            this.LendReturn1 = new HashSet<LendReturn>();
        }
    
        public int Id { get; set; }
        public System.DateTime From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int LendItemId { get; set; }
        public int UserId { get; set; }
        public int LenderUserId { get; set; }
        public Nullable<int> LendReturnId { get; set; }
    
        public virtual LendItem LendItem { get; set; }
        public virtual User User { get; set; }
        public virtual User LendUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LendReturn> LendReturn1 { get; set; }
        public virtual LendReturn LendReturn { get; set; }
    }
}
